### PR TITLE
Custom s3 port

### PR DESCRIPTION
**Pull request by sol1dus**
Hey. I'm using [fake-s3](https://github.com/jubos/fake-s3) in local environment, and there is a need to pass a port of s3 server. This PR adds the support of this. Thanks.

### CODE REVIEW

**Comment by digitaltoad** [comment]
I'm going to take a look at this later. From what I've read so far, we need this support, I'm just not sure it should be in the place that it is.



—
Josh

**Comment by sol1dus** [comment]
@digitaltoad okay, thank you. Leave your comments here please, I'll rewrite the implementation if it's needed

**Comment by sol1dus** [comment]
@digitaltoad now I see why it's not a good idea to put port directly in that json..

**Comment by digitaltoad** [comment]
fixed in #67

**Pull request closed without merging**
