### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Criten**
line 155 was missing a comma.

### CODE REVIEW

**Comment by Criten** [comment]
I believe this actually needs a few more changes.... in the doc we have it creating the S3Uploader and setting url in the S3Uploader to that set on the FileField... this changes where it checks for the signed url. I'm going to get my implementation and try a wack at improving the documentation.

**Comment by mcfiredrill** [comment]
I'm setting the url to hit my '/sign' action on my backend:
```
url: 'http://localhost:3000/sign'
```

Is this the intended usage?

**Comment by Criten** [comment]
@mcfiredrill yeah, so the place you want to set the sign endpoint inside the S3Uploader.create({}). I suggest using a relative url if you know your ember app will be on the same domain as your production API.

Ex.

``` javascript
import Ember from 'ember';
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  filesDidChange: (function() {
    var uploadUrl = this.get('url');
    var files = this.get('files');

    var uploader = EmberUploader.S3Uploader.create({
      url: 'api/v2/dashboard/sign'
    });
    ....
  }).observes('files')
});
```

**Comment by mcfiredrill** [comment]
Thanks, my code is working well:

```
import Ember from 'ember';
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  url: 'http://localhost:3000/sign',
  attributeBindings: ['image_url'],
  file: null,

  filesDidChange: (function() {
    var uploadUrl = this.get('url');
    var files = this.get('files');
    var that = this;

    var uploader = EmberUploader.S3Uploader.create({
      url: uploadUrl
    });

    uploader.on('didUpload', function(response) {
      // S3 will return XML with url
      var uploadedUrl = Ember.$(response).find('Location')[0].textContent;
      uploadedUrl = decodeURIComponent(uploadedUrl); // => http://yourbucket.s3.amazonaws.com/file.png
      console.log("UPLOADED ! : " + uploadedUrl);
      Ember.run(function() {
          that.set('image_url', uploadedUrl);
      });
    });

    uploader.on('progress', function(e) {
      console.log(e.percent);
    });

    if (!Ember.isEmpty(files)) {
      uploader.upload(files[0]); // Uploader will send a sign request then upload to S3
    }
  }).observes('files')
});

```
`image_url` is an attribute binding I needed...

**Pull request merged**
