### PR TITLE
 Give `headers` option for customizing HTTP headers

### PR DESCRIPTION
**Pull request by vsymguysung**
This option allows us to set the HTTP `headers` when a server requires any `headers` customizations.

### CODE REVIEW

**Comment by digitaltoad** [comment]
This is already in the s3 uploader code and is being deprecated. You can modify anything about the request using the `ajaxSettings` method. Take a look at [#98](/benefitcloud/ember-uploader/issues/98#issuecomment-171709241).

**Comment by digitaltoad** [comment]
This is being further modified in the 1.0 release by being just a hash that matches the configuration accepted by `jQuery.ajax` which is then merged with the required configuration for uploading.

**Comment by vsymguysung** [comment]
I don't see the 1.0 release for either `ember-uploader` or  `ember-cli-uploader`. Are you going to release it near future?  I am just checking it. BTW Thanks for your great work.

**Comment by digitaltoad** [comment]
@vsymguysung it is a work in progress at [1.0.0-cleanup](/benefitcloud/ember-uploader/tree/1.0.0-cleanup)

**Comment by vsymguysung** [comment]
:+1:

**Pull request closed without merging**
