### PR TITLE
DOC: Update Contributing Section of README

### PR DESCRIPTION
**Pull request by pootsbook**
Reflects new build process using Ember CLI instead of Grunt.

Please feel free to come back with corrections if some of this is not quite correct.

### CODE REVIEW

**Comment by digitaltoad** [comment]
This library isn't actually using Ember CLI, only Broccoli. However, I feel these docs should still be updated.

**Comment by pootsbook** [comment]
I got the impression from the [`.travis.yml`](https://github.com/benefitcloud/ember-uploader/blob/master/.travis.yml) that it was using Ember CLI for tests and build, is that not the case?

**Comment by digitaltoad** [comment]
Sorry you are correct. I'm not sure why I had thought this part of the library did not use ember-cli for builds and tests.

**Comment by pootsbook** [comment]
@digitaltoad No problem, thanks for merging. I was confused initially because I'd never seen Ember CLI used as a build tool for plugins and libraries that weren't actual Ember.js apps, but I've since seen it used quite a bit.

**Pull request merged**
