### PR TITLE
Bump ember-cli to v0.2.7 (latest)

### PR DESCRIPTION
**Pull request by quaertym**

### CODE REVIEW

**Comment by quaertym** [comment]
Travis does not build pull requests automatically. It says `pull requests disabled` in settings > requests.

**Comment by digitaltoad** [comment]
I've been meaning to update this. I'm going to tackle some of the outstanding issues this week. Before I merge this I want to make sure that I'm all set everywhere else. I'm also not sure there needs to be a separate ember-cli addon. I'm looking at combining the two and deprecating the actual ember-cli-uploader.

**Comment by quaertym** [comment]
@digitaltoad I find this repo very useful and I would like to make some series of contributions. If you can provide some leads on what you are working on, I would really love to help.

**Comment by digitaltoad** [comment]
Issue #35 is at the top of my list right now.

Another area that I feel needs work is the wiki explaining direct uploads with the S3Uploader. I need to update this area to make it easier for others to grok. Right now I only have a ruby example and its done by hand instead of using the aws-sdk which is much quicker to get up and running with. I would like to have a few examples in this area using different languages. Not everyone uses Ruby so I feel the wiki should accommodate them.

Lastly, I feel like a sister library for ember uploader that adds all of the actual UI stuff is what I want to tackle at some point. Upload buttons, dialogs, progress indicators, drag and drop. A kitchen sink of sorts. I'm not sure if the file component even belongs in this library.

**Comment by digitaltoad** [comment]
I should add that I feel the S3Uploader shouldn't make certain assumptions that it does. This would be addressed before the wiki updates, making it all around easier.

**Comment by quaertym** [comment]
Thanks, I think these are great improvements. I want to start with making `S3Uploader` customizable. As you said UI should belong to another addon that consumes `ember-uploader`. Documentation can be updated lastly I think. If you have some work on #35, I can leave that to you or tackle that as well if you want.

**Comment by digitaltoad** [comment]
Ill get #35 knocked out this week.



—
Josh

**Comment by quaertym** [comment]
By the way, we should merge this since current state of the repo is not working `(npm install fails when installing ember-cli)`.

**Comment by digitaltoad** [comment]
I hadn't had time to test against the newest version of cli or ember.



—
Josh

**Comment by quaertym** [comment]
Tests seem to be passing locally for the newest cli.

**Pull request merged**
