### PR TITLE
Upgrade to ember-cli 2.5.0

### PR DESCRIPTION
**Pull request by blimmer**
Tested locally and this all looks good.

### CODE REVIEW

**Comment by digitaltoad** [comment]
Thank you for the update!

**Comment by digitaltoad** [comment]
Looks like a lot of other changes got mixed in here mostly style/syntax. Can you clean that up a bit before the merge?

**Comment by blimmer** [comment]
That is all automagically done by `ember init`, e.g. [this](https://github.com/benefitcloud/ember-uploader/pull/115/files#diff-b667a856cecde4c39337505bb5725dc7L7) and [this](https://github.com/benefitcloud/ember-uploader/pull/115/files#diff-2be9329279338d3d4f10bea51caa639eR1). IMO we should keep these changes to make future `ember init`s produce less diffs and make the upgrade process easier.

**Comment by digitaltoad** [comment]
Fair enough. I would indeed like to keep it within the style of the community. I'll probably go back through and modify the eslint rules I've used to help a bit.

**Comment by blimmer** [comment]
Sounds like a great plan. Thank you.

**Pull request merged**
